import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Info } from "lucide-react";
import { PrivacySelector } from "./PrivacySelector";
import { PrivacyLevel } from "@/types/privacy";

interface EditRefererUrlFormProps {
  currentData: { url: string; privacy?: string; exceptions?: string[] };
  onSave: (data: { privacy: string; exceptions: string[] }) => void;
  onClose: () => void;
}

// The referral link itself (url/referral code) is always generated by the
// server from the account's own unique referral_code — it can't be typed in
// or pointed at someone else. The only thing to edit here is who can see it.
export const EditRefererUrlForm = ({ currentData, onSave, onClose }: EditRefererUrlFormProps) => {
  const [privacy, setPrivacy] = useState<PrivacyLevel>((currentData.privacy as PrivacyLevel) || "public");
  const [exceptions, setExceptions] = useState<string[]>(currentData.exceptions || []);

  const handleSave = () => {
    onSave({ privacy, exceptions });
    onClose();
  };

  return (
    <div className="space-y-4">
      <Alert className="bg-blue-50/50 dark:bg-blue-950/20 border-blue-200 dark:border-blue-800">
        <div className="flex gap-3">
          <Info className="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
          <AlertDescription className="text-sm leading-relaxed">
            Your referral link is generated automatically from your account and can't be changed.
            You can only control who can see it.
          </AlertDescription>
        </div>
      </Alert>

      {currentData.url && (
        <p className="text-sm break-all rounded-md border bg-muted/50 px-3 py-2 text-muted-foreground">
          {currentData.url}
        </p>
      )}

      <PrivacySelector
        value={privacy}
        onChange={(value) => setPrivacy(value as PrivacyLevel)}
        exceptions={exceptions}
        onExceptionsChange={setExceptions}
      />

      <div className="flex justify-end gap-2 pt-4">
        <Button type="button" variant="outline" onClick={onClose}>
          Cancel
        </Button>
        <Button type="button" onClick={handleSave}>Save Changes</Button>
      </div>
    </div>
  );
};