/**
 * CreateEventDialog.tsx
 * Mobile-first dialog for creating a Notable Event.
 *
 * Birthdays are auto-generated by the system from user profiles,
 * but Notable Events are created by users via this form.
 *
 * Optimistic UI:
 *  - On submit we immediately prepend the new event to window.__NOTABLE_EVENTS__
 *    and notify listeners via a 'notableEventCreated' CustomEvent.
 *  - A fire-and-forget POST to /api/events/create.php persists it on the backend.
 *  - No spinner — the card shows up instantly.
 */

import { useState, useMemo, useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { ImagePlus, X } from "lucide-react";

const MAX_IMAGES = 3;

export type CreatedEventType =
  | "wedding"
  | "burial"
  | "graduation"
  | "matriculation"
  | "child-dedication"
  | "house-warming"
  | "naming-ceremony"
  | "coronation"
  | "others";

export interface CreatedEvent {
  id: string;
  name: string;          // celebrant / honouree
  photo: string;         // cover image (first uploaded image, or initials fallback)
  images: string[];      // up to 3 uploaded photos/videos for the event
  dateLabel: string;     // e.g. "August 25"
  dateISO: string;       // YYYY-MM-DD
  eventType: CreatedEventType;
  eventLabel: string;    // human label
  notes?: string;
  isFriend: boolean;
  createdAt: string;
}

const EVENT_OPTIONS: { value: CreatedEventType; label: string }[] = [
  { value: "wedding",          label: "Wedding / Marriage" },
  { value: "burial",           label: "Burial" },
  { value: "graduation",       label: "Graduation" },
  { value: "matriculation",    label: "Matriculation" },
  { value: "child-dedication", label: "Child Dedication" },
  { value: "house-warming",    label: "House Warming" },
  { value: "naming-ceremony",  label: "Naming Ceremony" },
  { value: "coronation",       label: "Coronation" },
  { value: "others",           label: "Others (specify)" },
];

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const formatHumanDate = (iso: string) => {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  if (!y || !m || !d) return iso;
  return `${MONTHS[m - 1]} ${d}`;
};

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onCreated?: (ev: CreatedEvent) => void;
}

export const CreateEventDialog = ({ isOpen, onClose, onCreated }: Props) => {
  const { toast } = useToast();
  const [name,      setName]      = useState("");
  const [type,      setType]      = useState<CreatedEventType>("wedding");
  const [customType, setCustomType] = useState("");
  const [dateISO,   setDateISO]   = useState("");
  const [notes,     setNotes]     = useState("");
  const [submitting, setSubmitting] = useState(false);

  const todayISO = useMemo(() => {
    const d = new Date();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    return `${d.getFullYear()}-${mm}-${dd}`;
  }, []);

  const reset = () => {
    setName("");
    setType("wedding");
    setCustomType("");
    setDateISO("");
    setNotes("");
    setSubmitting(false);
  };

  const close = () => {
    reset();
    onClose();
  };

  const canSubmit =
    name.trim().length >= 2 &&
    !!dateISO &&
    (type !== "others" || customType.trim().length >= 2);

  const handleSubmit = () => {
    if (!canSubmit) return;
    setSubmitting(true);

    const resolvedLabel =
      type === "others"
        ? customType.trim()
        : EVENT_OPTIONS.find(o => o.value === type)?.label ?? "Event";

    const id = `evt-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
    const photo = `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(name.trim())}`;

    const newEvent: CreatedEvent = {
      id,
      name: name.trim(),
      photo,
      dateLabel: formatHumanDate(dateISO),
      dateISO,
      eventType: type,
      eventLabel: resolvedLabel,
      notes: notes.trim() || undefined,
      isFriend: false,
      createdAt: new Date().toISOString(),
    };

    // ── Optimistic: prepend to window store + broadcast ──────────────────────
    if (typeof window !== "undefined") {
      const w = window as any;
      const existing: CreatedEvent[] = Array.isArray(w.__NOTABLE_EVENTS__) ? w.__NOTABLE_EVENTS__ : [];
      w.__NOTABLE_EVENTS__ = [newEvent, ...existing];
      window.dispatchEvent(new CustomEvent("notableEventCreated", { detail: newEvent }));
    }

    // Notify caller immediately
    onCreated?.(newEvent);

    toast({
      title: "Event created",
      description: `${resolvedLabel} for ${newEvent.name} on ${newEvent.dateLabel} is now live.`,
    });

    // ── Fire-and-forget backend persistence ──────────────────────────────────
    const API_BASE =
      (import.meta as any).env?.VITE_API_URL ||
      "https://angola-press.com/en/api";
    fetch(`${API_BASE}/events/create.php`, {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id:  id,
        name:       newEvent.name,
        event_type: type,
        event_label: resolvedLabel,
        event_date: dateISO,
        notes:      newEvent.notes ?? "",
      }),
    }).catch(() => { /* silent — optimistic */ });

    close();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(o) => !o && close()}>
      <DialogContent className="w-[calc(100vw-0.5rem)] sm:w-full sm:max-w-[520px] max-h-[92dvh] overflow-y-auto px-3 py-4 sm:p-6">
        <DialogHeader className="text-left pr-6">
          <DialogTitle className="text-lg font-bold break-words">Create Notable Event</DialogTitle>
          <DialogDescription className="text-[13px] leading-relaxed">
            Birthdays appear automatically from profile info. Add weddings, burials,
            graduations and other occasions here so friends can celebrate with you.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3.5 mt-2">
          {/* Celebrant / Honouree */}
          <div className="space-y-1.5">
            <Label htmlFor="ev-name" className="text-sm font-semibold">
              Celebrant / Honouree Name <span className="text-destructive">*</span>
            </Label>
            <Input
              id="ev-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Anthony Okafor Ejiro"
              className="text-base"
              maxLength={80}
            />
          </div>

          {/* Event type */}
          <div className="space-y-1.5">
            <Label className="text-sm font-semibold">
              Event Type <span className="text-destructive">*</span>
            </Label>
            <Select value={type} onValueChange={(v) => setType(v as CreatedEventType)}>
              <SelectTrigger className="text-base h-11">
                <SelectValue placeholder="Choose an event type" />
              </SelectTrigger>
              <SelectContent>
                {EVENT_OPTIONS.map(o => (
                  <SelectItem key={o.value} value={o.value} className="text-base">
                    {o.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {type === "others" && (
              <Input
                value={customType}
                onChange={(e) => setCustomType(e.target.value)}
                placeholder="Specify event (e.g. Anniversary)"
                className="text-base mt-2"
                maxLength={60}
              />
            )}
          </div>

          {/* Date */}
          <div className="space-y-1.5">
            <Label htmlFor="ev-date" className="text-sm font-semibold">
              Event Date <span className="text-destructive">*</span>
            </Label>
            <Input
              id="ev-date"
              type="date"
              value={dateISO}
              min={todayISO.slice(0, 4) + "-01-01"}
              onChange={(e) => setDateISO(e.target.value)}
              className="text-base h-11"
            />
            {dateISO && (
              <p className="text-[12px] text-muted-foreground">
                Shows on cards as <span className="font-semibold text-foreground">{formatHumanDate(dateISO)}</span>.
              </p>
            )}
          </div>

          {/* Notes (optional) */}
          <div className="space-y-1.5">
            <Label htmlFor="ev-notes" className="text-sm font-semibold">
              Notes <span className="text-muted-foreground font-normal">(optional)</span>
            </Label>
            <Textarea
              id="ev-notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Venue, dress code, time — anything friends should know."
              className="text-[15px] min-h-[80px] resize-none"
              maxLength={280}
            />
            <p className="text-[11px] text-muted-foreground text-right">{notes.length}/280</p>
          </div>
        </div>

        <DialogFooter className="flex flex-col-reverse sm:flex-row sm:justify-end gap-2 pt-2">
          <Button variant="outline" onClick={close} className="w-full sm:w-auto" disabled={submitting}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={!canSubmit || submitting} className="w-full sm:w-auto font-bold">
            Publish Event
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default CreateEventDialog;
