/**
 * CreateEventDialog.tsx
 * Mobile-first dialog for creating a Notable Event.
 *
 * Birthdays are auto-generated by the system from user profiles,
 * but Notable Events are created by users via this form.
 *
 * Celebrants:
 *  - The Poster is NOT necessarily the Celebrant.
 *  - An event can have up to 10 Celebrants, each with an optional status/role
 *    (e.g. Chief Celebrant, Co-Celebrant, Groom, Bride…).
 *  - Each Celebrant can have images attached from THREE sources:
 *      1. Media Uploader  — up to 3 images.
 *      2. My Profile Picture — one image (the Poster's own avatar).
 *      3. A Friend's Profile Picture — one image, chosen from the Poster's
 *         Friends List. The tagged Friend MUST approve the event for it to go
 *         live; until then it is visible only to the Poster and auto-expires
 *         when the Event Date passes.
 *
 * Optimistic UI:
 *  - On submit we immediately prepend the new event to window.__NOTABLE_EVENTS__
 *    and notify listeners via a 'notableEventCreated' CustomEvent.
 *  - A fire-and-forget POST to /api/events/create.php persists it on the backend.
 *  - No spinner — the card shows up instantly.
 */

import { useState, useMemo, useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { useUserProfile } from "@/hooks/useWindowData";
import { FriendsListSearch, Friend } from "@/components/profile/FriendsListSearch";
import {
  ImagePlus, X, Globe, Users, UserCheck, Lock, Plus, Trash2,
  UserCircle2, UserPlus, Crown, Clock, CheckCircle2, User as UserIcon,
} from "lucide-react";

const MAX_IMAGES = 3;
const MAX_CELEBRANTS = 10;

export type CreatedEventType =
  | "wedding"
  | "burial"
  | "graduation"
  | "matriculation"
  | "child-dedication"
  | "house-warming"
  | "naming-ceremony"
  | "coronation"
  | "anniversary"
  | "award-nite"
  | "birthday"
  | "convocation"
  | "inauguration"
  | "investiture"
  | "induction"
  | "initiation"
  | "swearing-in"
  | "title-conferment"
  | "title-taking"
  | "ordination"
  | "others";

/** Who is allowed to see this Notable Event. */
export type EventAudience =
  | "public"
  | "friends"
  | "friends-of-friends"
  | "only-me";

const AUDIENCE_OPTIONS: {
  value: EventAudience;
  label: string;
  hint: string;
  icon: typeof Globe;
}[] = [
  { value: "public",             label: "Public",             hint: "Anyone on Mobigate can see this event.", icon: Globe },
  { value: "friends",            label: "Friends",            hint: "Only your friends can see this event.", icon: Users },
  { value: "friends-of-friends", label: "Friends of Friends", hint: "Your friends and their friends can see it.", icon: UserCheck },
  { value: "only-me",            label: "Only Me",            hint: "Private — only you can see this event.", icon: Lock },
];

/** A friend tagged on a celebrant, with their approval state. */
export interface CelebrantFriendTag {
  friendId: string;
  friendName: string;
  friendImage: string;
  /** A tagged friend must approve before the event can go live. */
  approval: "pending" | "approved" | "cancelled";
}

/** A single celebrant / honouree on an event. */
export interface EventCelebrant {
  id: string;
  name: string;
  /** Optional status, e.g. "Chief Celebrant", "Co-Celebrant", "Groom". */
  role?: string;
  /** Up to 3 images from the media uploader. */
  uploadedImages: string[];
  /** The Poster's own profile picture, if added for this celebrant. */
  myProfileImage?: string;
  /** A friend's profile picture (requires that friend's approval). */
  friendTag?: CelebrantFriendTag;
}

export interface CreatedEvent {
  id: string;
  name: string;          // primary celebrant / honouree (first celebrant)
  photo: string;         // cover image (first available image, or initials fallback)
  images: string[];      // all celebrant images flattened (for galleries/counts)
  celebrants: EventCelebrant[];  // up to 10 celebrants
  dateLabel: string;     // e.g. "August 25"
  dateISO: string;       // YYYY-MM-DD
  eventType: CreatedEventType;
  eventLabel: string;    // human label
  notes?: string;
  audience: EventAudience;   // who can see this event
  /** "live" once all friend tags are approved; "pending-approval" otherwise. */
  status: "live" | "pending-approval";
  isFriend: boolean;
  postedBy?: { id: string; name: string };
  createdAt: string;
}

const EVENT_OPTIONS: { value: CreatedEventType; label: string }[] = [
  { value: "wedding",          label: "Wedding / Marriage" },
  { value: "burial",           label: "Burial" },
  { value: "graduation",       label: "Graduation" },
  { value: "matriculation",    label: "Matriculation" },
  { value: "child-dedication", label: "Child Dedication" },
  { value: "house-warming",    label: "House Warming" },
  { value: "naming-ceremony",  label: "Naming Ceremony" },
  { value: "coronation",       label: "Coronation" },
  { value: "anniversary",      label: "Anniversary" },
  { value: "award-nite",       label: "Award Nite" },
  { value: "birthday",         label: "Birthday" },
  { value: "convocation",      label: "Convocation" },
  { value: "inauguration",     label: "Inauguration" },
  { value: "investiture",      label: "Investiture" },
  { value: "induction",        label: "Induction" },
  { value: "initiation",       label: "Initiation" },
  { value: "swearing-in",      label: "Swearing-in" },
  { value: "title-conferment", label: "Title Conferment" },
  { value: "title-taking",     label: "Title Taking" },
  { value: "ordination",       label: "Ordination" },
  { value: "others",           label: "Others (specify)" },
];

/** Optional status presets for celebrants. */
const ROLE_OPTIONS = [
  "Chief Celebrant",
  "Co-Celebrant",
  "Celebrant",
  "Groom",
  "Bride",
  "Honouree",
  "Guest of Honour",
  "Other",
];

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const formatHumanDate = (iso: string) => {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  if (!y || !m || !d) return iso;
  return `${MONTHS[m - 1]} ${d}`;
};

/** All images attached to a celebrant, in display order. */
const celebrantImages = (c: EventCelebrant): string[] => {
  const list: string[] = [...c.uploadedImages];
  if (c.myProfileImage) list.push(c.myProfileImage);
  if (c.friendTag?.friendImage) list.push(c.friendTag.friendImage);
  return list;
};

const newCelebrant = (): EventCelebrant => ({
  id: `cel-${Date.now()}-${Math.floor(Math.random() * 1e6)}`,
  name: "",
  role: "",
  uploadedImages: [],
});

/* ────────────────────────────────────────────────────────────────────────────
   Celebrant card — defined OUTSIDE the main component to keep a stable identity
   across re-renders (prevents mobile keyboard focus loss).
   ──────────────────────────────────────────────────────────────────────────── */
interface CelebrantCardProps {
  celebrant: EventCelebrant;
  index: number;
  total: number;
  myAvatar: string;
  myName: string;
  onChange: (id: string, patch: Partial<EventCelebrant>) => void;
  onRemove: (id: string) => void;
  onPickFriend: (id: string) => void;
  onToast: (t: { title: string; description?: string; variant?: "destructive" }) => void;
}

const CelebrantCard = ({
  celebrant, index, total, myAvatar, myName,
  onChange, onRemove, onPickFriend, onToast,
}: CelebrantCardProps) => {
  const fileRef = useRef<HTMLInputElement>(null);
  const imgs = celebrantImages(celebrant);
  const uploadCount = celebrant.uploadedImages.length;

  const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    if (files.length === 0) return;
    const remaining = MAX_IMAGES - uploadCount;
    if (remaining <= 0) {
      onToast({ title: "Maximum reached", description: `Up to ${MAX_IMAGES} uploaded images per celebrant.`, variant: "destructive" });
      e.target.value = "";
      return;
    }
    const accepted = files.slice(0, remaining);
    if (files.length > remaining) {
      onToast({ title: "Some images skipped", description: `Only ${MAX_IMAGES} uploads allowed — added the first ${remaining}.` });
    }
    accepted.forEach((file) => {
      const reader = new FileReader();
      reader.onload = () => {
        if (typeof reader.result === "string") {
          onChange(celebrant.id, {
            uploadedImages: [
              ...celebrant.uploadedImages,
              reader.result as string,
            ].slice(0, MAX_IMAGES),
          });
        }
      };
      reader.readAsDataURL(file);
    });
    e.target.value = "";
  };

  const removeUpload = (idx: number) =>
    onChange(celebrant.id, { uploadedImages: celebrant.uploadedImages.filter((_, i) => i !== idx) });

  const toggleMyProfile = () => {
    if (celebrant.myProfileImage) {
      onChange(celebrant.id, { myProfileImage: undefined });
    } else {
      if (!myAvatar) {
        onToast({ title: "No profile picture", description: "Your profile has no picture to add.", variant: "destructive" });
        return;
      }
      onChange(celebrant.id, { myProfileImage: myAvatar });
    }
  };

  const removeFriendTag = () => onChange(celebrant.id, { friendTag: undefined });

  return (
    <div className="rounded-xl border border-border bg-muted/30 p-3 space-y-3">
      {/* Header row */}
      <div className="flex items-center justify-between gap-2">
        <span className="inline-flex items-center gap-1.5 text-[13px] font-bold text-foreground">
          <Crown className="h-3.5 w-3.5 text-primary" />
          Celebrant {index + 1}
        </span>
        {total > 1 && (
          <button
            type="button"
            onClick={() => onRemove(celebrant.id)}
            className="inline-flex items-center gap-1 rounded-md px-2 py-1 text-[12px] font-semibold text-destructive hover:bg-destructive/10 active:scale-95 transition-all touch-manipulation"
          >
            <Trash2 className="h-3.5 w-3.5" /> Remove
          </button>
        )}
      </div>

      {/* Name */}
      <div className="space-y-1.5">
        <Label className="text-[13px] font-semibold">
          Celebrant Name <span className="text-destructive">*</span>
        </Label>
        <Input
          value={celebrant.name}
          onChange={(e) => onChange(celebrant.id, { name: e.target.value })}
          placeholder="e.g. Anthony Okafor Ejiro"
          className="text-base"
          maxLength={80}
        />
      </div>

      {/* Status / role (optional) */}
      <div className="space-y-1.5">
        <Label className="text-[13px] font-semibold">
          Status <span className="text-muted-foreground font-normal">(optional)</span>
        </Label>
        <Select
          value={ROLE_OPTIONS.includes(celebrant.role || "") ? celebrant.role : (celebrant.role ? "Other" : "")}
          onValueChange={(v) => onChange(celebrant.id, { role: v === "Other" ? " " : v })}
        >
          <SelectTrigger className="text-base h-11">
            <SelectValue placeholder="e.g. Chief Celebrant, Groom, Bride" />
          </SelectTrigger>
          <SelectContent>
            {ROLE_OPTIONS.map((r) => (
              <SelectItem key={r} value={r} className="text-base">{r}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        {celebrant.role !== undefined && celebrant.role !== "" && !ROLE_OPTIONS.includes(celebrant.role) && (
          <Input
            value={celebrant.role.trim()}
            onChange={(e) => onChange(celebrant.id, { role: e.target.value || " " })}
            placeholder="Specify status"
            className="text-base mt-1"
            maxLength={40}
            autoFocus
          />
        )}
      </div>

      {/* Images */}
      <div className="space-y-2">
        <Label className="text-[13px] font-semibold">
          Photos <span className="text-muted-foreground font-normal">(optional)</span>
        </Label>

        {/* Source 1: media uploader thumbnails */}
        <div className="grid grid-cols-3 gap-2">
          {celebrant.uploadedImages.map((src, idx) => (
            <div key={idx} className="relative aspect-square rounded-lg overflow-hidden border border-border bg-muted">
              <img src={src} alt={`Photo ${idx + 1}`} className="w-full h-full object-cover" />
              <button
                type="button"
                onClick={() => removeUpload(idx)}
                className="absolute top-1 right-1 h-6 w-6 rounded-full bg-black/60 text-white flex items-center justify-center hover:bg-black/80 active:scale-90 transition-all touch-manipulation"
                aria-label={`Remove photo ${idx + 1}`}
              >
                <X className="h-3.5 w-3.5" />
              </button>
            </div>
          ))}
          {uploadCount < MAX_IMAGES && (
            <button
              type="button"
              onClick={() => fileRef.current?.click()}
              className="aspect-square rounded-lg border-2 border-dashed border-border bg-muted/40 flex flex-col items-center justify-center gap-1 text-muted-foreground hover:border-primary/50 hover:text-primary active:scale-[0.98] transition-all touch-manipulation"
              aria-label="Upload photo"
            >
              <ImagePlus className="h-5 w-5" />
              <span className="text-[10px] font-semibold leading-tight text-center">Upload<br />({uploadCount}/{MAX_IMAGES})</span>
            </button>
          )}
        </div>
        <input ref={fileRef} type="file" accept="image/*" multiple className="hidden" onChange={handleUpload} />

        {/* Source 2 & 3: profile-picture quick adds */}
        <div className="grid grid-cols-2 gap-2">
          <button
            type="button"
            onClick={toggleMyProfile}
            aria-pressed={!!celebrant.myProfileImage}
            className={`flex items-center gap-2 rounded-lg border p-2 text-left transition-all touch-manipulation active:scale-[0.98] ${
              celebrant.myProfileImage ? "border-primary bg-primary/10 ring-1 ring-primary" : "border-border bg-background hover:border-primary/40"
            }`}
          >
            <UserCircle2 className={`h-5 w-5 shrink-0 ${celebrant.myProfileImage ? "text-primary" : "text-muted-foreground"}`} />
            <span className="text-[12px] font-semibold leading-tight">
              {celebrant.myProfileImage ? "My photo added" : "Add My Profile Picture"}
            </span>
          </button>

          <button
            type="button"
            onClick={() => onPickFriend(celebrant.id)}
            aria-pressed={!!celebrant.friendTag}
            className={`flex items-center gap-2 rounded-lg border p-2 text-left transition-all touch-manipulation active:scale-[0.98] ${
              celebrant.friendTag ? "border-primary bg-primary/10 ring-1 ring-primary" : "border-border bg-background hover:border-primary/40"
            }`}
          >
            <UserPlus className={`h-5 w-5 shrink-0 ${celebrant.friendTag ? "text-primary" : "text-muted-foreground"}`} />
            <span className="text-[12px] font-semibold leading-tight">
              {celebrant.friendTag ? "Friend tagged" : "Add Friend's Picture"}
            </span>
          </button>
        </div>

        {/* My profile preview chip */}
        {celebrant.myProfileImage && (
          <div className="flex items-center gap-2 rounded-lg border border-border bg-background px-2 py-1.5">
            <Avatar className="h-8 w-8">
              <AvatarImage src={celebrant.myProfileImage} alt={myName} />
              <AvatarFallback><UserIcon className="h-4 w-4" /></AvatarFallback>
            </Avatar>
            <span className="min-w-0 flex-1 text-[12px] font-medium truncate">{myName || "Me"} (your picture)</span>
            <button type="button" onClick={toggleMyProfile} className="text-muted-foreground hover:text-destructive active:scale-90 transition-all" aria-label="Remove my picture">
              <X className="h-4 w-4" />
            </button>
          </div>
        )}

        {/* Friend tag chip + approval status */}
        {celebrant.friendTag && (
          <div className="flex items-center gap-2 rounded-lg border border-border bg-background px-2 py-1.5">
            <Avatar className="h-8 w-8">
              <AvatarImage src={celebrant.friendTag.friendImage} alt={celebrant.friendTag.friendName} />
              <AvatarFallback><UserIcon className="h-4 w-4" /></AvatarFallback>
            </Avatar>
            <span className="min-w-0 flex-1">
              <span className="block text-[12px] font-semibold truncate">{celebrant.friendTag.friendName}</span>
              <span className="inline-flex items-center gap-1 text-[10.5px] font-medium text-amber-600">
                <Clock className="h-3 w-3" /> Awaiting approval
              </span>
            </span>
            <button type="button" onClick={removeFriendTag} className="text-muted-foreground hover:text-destructive active:scale-90 transition-all" aria-label="Remove friend tag">
              <X className="h-4 w-4" />
            </button>
          </div>
        )}

        {imgs.length === 0 && (
          <p className="text-[11px] text-muted-foreground">No photos yet — upload, or add a profile picture.</p>
        )}
      </div>
    </div>
  );
};

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onCreated?: (ev: CreatedEvent) => void;
}

export const CreateEventDialog = ({ isOpen, onClose, onCreated }: Props) => {
  const { toast } = useToast();
  const profile = useUserProfile();
  const myAvatar = profile?.avatar || "";
  const myName = profile?.fullName || profile?.username || "Me";

  const [celebrants, setCelebrants] = useState<EventCelebrant[]>(() => [newCelebrant()]);
  const [type,      setType]      = useState<CreatedEventType>("wedding");
  const [customType, setCustomType] = useState("");
  const [dateISO,   setDateISO]   = useState("");
  const [notes,     setNotes]     = useState("");
  const [audience,  setAudience]  = useState<EventAudience>("public");
  const [submitting, setSubmitting] = useState(false);

  // Friend picker state — tracks which celebrant is choosing a friend.
  const [friendPickerFor, setFriendPickerFor] = useState<string | null>(null);

  const todayISO = useMemo(() => {
    const d = new Date();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    return `${d.getFullYear()}-${mm}-${dd}`;
  }, []);

  const updateCelebrant = (id: string, patch: Partial<EventCelebrant>) =>
    setCelebrants((prev) => prev.map((c) => (c.id === id ? { ...c, ...patch } : c)));

  const addCelebrant = () => {
    if (celebrants.length >= MAX_CELEBRANTS) {
      toast({ title: "Maximum reached", description: `Up to ${MAX_CELEBRANTS} celebrants per event.`, variant: "destructive" });
      return;
    }
    setCelebrants((prev) => [...prev, newCelebrant()]);
  };

  const removeCelebrant = (id: string) =>
    setCelebrants((prev) => (prev.length <= 1 ? prev : prev.filter((c) => c.id !== id)));

  const handleSelectFriend = (friend: Friend) => {
    if (!friendPickerFor) return;
    const image = friend.profileImage || `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(friend.name)}`;
    updateCelebrant(friendPickerFor, {
      friendTag: {
        friendId: friend.id,
        friendName: friend.name,
        friendImage: image,
        approval: "pending",
      },
    });
    toast({
      title: "Friend tagged",
      description: `${friend.name} will be notified to approve this event.`,
    });
    setFriendPickerFor(null);
  };

  const reset = () => {
    setCelebrants([newCelebrant()]);
    setType("wedding");
    setCustomType("");
    setDateISO("");
    setNotes("");
    setAudience("public");
    setSubmitting(false);
    setFriendPickerFor(null);
  };

  const close = () => {
    reset();
    onClose();
  };

  const validCelebrants = celebrants.filter((c) => c.name.trim().length >= 2);
  const hasPendingApproval = celebrants.some((c) => c.friendTag && c.friendTag.approval === "pending");

  const canSubmit =
    validCelebrants.length >= 1 &&
    !!dateISO &&
    (type !== "others" || customType.trim().length >= 2);

  const handleSubmit = () => {
    if (!canSubmit) return;
    setSubmitting(true);

    const resolvedLabel =
      type === "others"
        ? customType.trim()
        : EVENT_OPTIONS.find(o => o.value === type)?.label ?? "Event";

    // Normalise celebrants (trim names/roles, drop empties).
    const finalCelebrants: EventCelebrant[] = validCelebrants.map((c) => ({
      ...c,
      name: c.name.trim(),
      role: c.role && c.role.trim() ? c.role.trim() : undefined,
    }));

    const primary = finalCelebrants[0];
    const allImages = finalCelebrants.flatMap(celebrantImages);

    const id = `evt-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
    const initialsAvatar = `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(primary.name)}`;
    const photo = allImages[0] || initialsAvatar;

    const newEvent: CreatedEvent = {
      id,
      name: primary.name,
      photo,
      images: allImages,
      celebrants: finalCelebrants,
      dateLabel: formatHumanDate(dateISO),
      dateISO,
      eventType: type,
      eventLabel: resolvedLabel,
      notes: notes.trim() || undefined,
      audience,
      status: hasPendingApproval ? "pending-approval" : "live",
      isFriend: false,
      postedBy: profile ? { id: profile.id, name: myName } : undefined,
      createdAt: new Date().toISOString(),
    };

    // ── Optimistic: prepend to window store + broadcast ──────────────────────
    if (typeof window !== "undefined") {
      const w = window as any;
      const existing: CreatedEvent[] = Array.isArray(w.__NOTABLE_EVENTS__) ? w.__NOTABLE_EVENTS__ : [];
      w.__NOTABLE_EVENTS__ = [newEvent, ...existing];
      window.dispatchEvent(new CustomEvent("notableEventCreated", { detail: newEvent }));

      // Notify any tagged friends so they can Approve / Cancel the event.
      finalCelebrants.forEach((c) => {
        if (c.friendTag && c.friendTag.approval === "pending") {
          window.dispatchEvent(new CustomEvent("eventCelebrantTagged", {
            detail: {
              eventId: id,
              eventLabel: resolvedLabel,
              eventDate: dateISO,
              celebrantId: c.id,
              celebrantName: c.name,
              friendId: c.friendTag.friendId,
              friendName: c.friendTag.friendName,
              postedBy: newEvent.postedBy,
            },
          }));
        }
      });
    }

    onCreated?.(newEvent);

    toast({
      title: hasPendingApproval ? "Event created — awaiting approval" : "Event created",
      description: hasPendingApproval
        ? `Tagged friends must approve before this event goes live. It auto-expires after ${newEvent.dateLabel} if not approved.`
        : `${resolvedLabel} for ${newEvent.name} on ${newEvent.dateLabel} is now live.`,
    });

    // ── Fire-and-forget backend persistence ──────────────────────────────────
    const API_BASE =
      (import.meta as any).env?.VITE_API_URL ||
      "https://angola-press.com/en/api";
    fetch(`${API_BASE}/events/create.php`, {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id:  id,
        event_type: type,
        event_label: resolvedLabel,
        event_date: dateISO,
        notes:      newEvent.notes ?? "",
        audience:   newEvent.audience,
        status:     newEvent.status,
        celebrants: finalCelebrants.map((c) => ({
          name: c.name,
          role: c.role ?? "",
          images: c.uploadedImages,
          my_profile_image: c.myProfileImage ?? "",
          friend: c.friendTag
            ? { id: c.friendTag.friendId, name: c.friendTag.friendName, approval: c.friendTag.approval }
            : null,
        })),
      }),
    }).catch(() => { /* silent — optimistic */ });

    close();
  };

  return (
    <>
      <Dialog open={isOpen} onOpenChange={(o) => !o && close()}>
        <DialogContent className="w-[calc(100vw-0.5rem)] sm:w-full sm:max-w-[520px] max-h-[92dvh] overflow-y-auto px-3 py-4 sm:p-6">
          <DialogHeader className="text-left pr-6">
            <DialogTitle className="text-lg font-bold break-words">Create Notable Event</DialogTitle>
            <DialogDescription className="text-[13px] leading-relaxed">
              You don't have to be the celebrant. Add up to {MAX_CELEBRANTS} celebrants, give each an
              optional status, and attach their photos. Tagging a friend's picture sends them a
              request to approve the event.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3.5 mt-2">
            {/* Celebrants */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-sm font-semibold">
                  Add Celebrants <span className="text-destructive">*</span>
                </Label>
                <span className="text-[11px] text-muted-foreground">{celebrants.length}/{MAX_CELEBRANTS}</span>
              </div>

              <div className="space-y-3">
                {celebrants.map((c, i) => (
                  <CelebrantCard
                    key={c.id}
                    celebrant={c}
                    index={i}
                    total={celebrants.length}
                    myAvatar={myAvatar}
                    myName={myName}
                    onChange={updateCelebrant}
                    onRemove={removeCelebrant}
                    onPickFriend={(id) => setFriendPickerFor(id)}
                    onToast={toast}
                  />
                ))}
              </div>

              {celebrants.length < MAX_CELEBRANTS && (
                <Button
                  type="button"
                  variant="outline"
                  onClick={addCelebrant}
                  className="w-full font-semibold touch-manipulation"
                >
                  <Plus className="h-4 w-4 mr-1" /> Add Another Celebrant
                </Button>
              )}
            </div>

            {/* Event type */}
            <div className="space-y-1.5">
              <Label className="text-sm font-semibold">
                Event Type <span className="text-destructive">*</span>
              </Label>
              <Select value={type} onValueChange={(v) => setType(v as CreatedEventType)}>
                <SelectTrigger className="text-base h-11">
                  <SelectValue placeholder="Choose an event type" />
                </SelectTrigger>
                <SelectContent className="max-h-[60dvh] overflow-y-auto">
                  {EVENT_OPTIONS.map(o => (
                    <SelectItem key={o.value} value={o.value} className="text-base">
                      {o.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {type === "others" && (
                <Input
                  value={customType}
                  onChange={(e) => setCustomType(e.target.value)}
                  placeholder="Specify event (e.g. Anniversary)"
                  className="text-base mt-2"
                  maxLength={60}
                />
              )}
            </div>

            {/* Date */}
            <div className="space-y-1.5">
              <Label htmlFor="ev-date" className="text-sm font-semibold">
                Event Date <span className="text-destructive">*</span>
              </Label>
              <Input
                id="ev-date"
                type="date"
                value={dateISO}
                min={todayISO.slice(0, 4) + "-01-01"}
                onChange={(e) => setDateISO(e.target.value)}
                className="text-base h-11"
              />
              {dateISO && (
                <p className="text-[12px] text-muted-foreground">
                  Shows on cards as <span className="font-semibold text-foreground">{formatHumanDate(dateISO)}</span>.
                </p>
              )}
            </div>

            {/* Notes */}
            <div className="space-y-1.5">
              <Label htmlFor="ev-notes" className="text-sm font-semibold">
                Notes <span className="text-muted-foreground font-normal">(optional)</span>
              </Label>
              <Textarea
                id="ev-notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Venue, dress code, time — anything friends should know."
                className="text-[15px] min-h-[80px] resize-none"
                maxLength={280}
              />
              <p className="text-[11px] text-muted-foreground text-right">{notes.length}/280</p>
            </div>

            {/* Audience / Privacy */}
            <div className="space-y-1.5">
              <Label className="text-sm font-semibold">
                Audience <span className="text-destructive">*</span>
              </Label>
              <p className="text-[12px] text-muted-foreground leading-snug">
                Choose who is allowed to see this event.
              </p>
              <div className="grid grid-cols-2 gap-2">
                {AUDIENCE_OPTIONS.map((o) => {
                  const Icon = o.icon;
                  const active = audience === o.value;
                  return (
                    <button
                      key={o.value}
                      type="button"
                      onClick={() => setAudience(o.value)}
                      aria-pressed={active}
                      className={`flex items-start gap-2 rounded-lg border p-2.5 text-left transition-all touch-manipulation active:scale-[0.98] ${
                        active
                          ? "border-primary bg-primary/10 ring-1 ring-primary"
                          : "border-border bg-muted/40 hover:border-primary/40"
                      }`}
                    >
                      <Icon className={`h-4 w-4 mt-0.5 shrink-0 ${active ? "text-primary" : "text-muted-foreground"}`} />
                      <span className="min-w-0">
                        <span className={`block text-[13px] font-semibold leading-tight ${active ? "text-primary" : "text-foreground"}`}>
                          {o.label}
                        </span>
                        <span className="block text-[11px] text-muted-foreground leading-snug mt-0.5">
                          {o.hint}
                        </span>
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Pending approval notice */}
            {hasPendingApproval && (
              <div className="flex items-start gap-2 rounded-lg border border-amber-300 bg-amber-50 dark:bg-amber-950/30 p-2.5">
                <Clock className="h-4 w-4 text-amber-600 mt-0.5 shrink-0" />
                <p className="text-[12px] text-amber-700 dark:text-amber-400 leading-snug">
                  You tagged a friend's picture. The event stays private to you until they
                  <span className="font-semibold"> Approve Event</span>. If unapproved, it auto-deletes after the event date.
                </p>
              </div>
            )}
          </div>

          <DialogFooter className="flex flex-col-reverse sm:flex-row sm:justify-end gap-2 pt-2">
            <Button variant="outline" onClick={close} className="w-full sm:w-auto" disabled={submitting}>
              Cancel
            </Button>
            <Button onClick={handleSubmit} disabled={!canSubmit || submitting} className="w-full sm:w-auto font-bold">
              {hasPendingApproval ? (
                <><Clock className="h-4 w-4 mr-1" /> Create & Request Approval</>
              ) : (
                <><CheckCircle2 className="h-4 w-4 mr-1" /> Publish Event</>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Friend picker — nested dialog for "Add Friend's Profile Picture" */}
      <FriendsListSearch
        open={friendPickerFor !== null}
        onOpenChange={(o) => { if (!o) setFriendPickerFor(null); }}
        onSelect={handleSelectFriend}
      />
    </>
  );
};

export default CreateEventDialog;
