/**
 * CreateEventDialog.tsx
 * Mobile-first dialog for creating a Notable Event.
 *
 * Birthdays are auto-generated by the system from user profiles,
 * but Notable Events are created by users via this form.
 *
 * Optimistic UI:
 *  - On submit we immediately prepend the new event to window.__NOTABLE_EVENTS__
 *    and notify listeners via a 'notableEventCreated' CustomEvent.
 *  - A fire-and-forget POST to /api/events/create.php persists it on the backend.
 *  - No spinner — the card shows up instantly.
 */

import { useState, useMemo, useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { ImagePlus, X, Globe, Users, UserCheck, Lock } from "lucide-react";

const MAX_IMAGES = 3;

export type CreatedEventType =
  | "wedding"
  | "burial"
  | "graduation"
  | "matriculation"
  | "child-dedication"
  | "house-warming"
  | "naming-ceremony"
  | "coronation"
  | "anniversary"
  | "award-nite"
  | "birthday"
  | "convocation"
  | "inauguration"
  | "investiture"
  | "induction"
  | "initiation"
  | "swearing-in"
  | "title-conferment"
  | "title-taking"
  | "ordination"
  | "others";

/** Who is allowed to see this Notable Event. */
export type EventAudience =
  | "public"
  | "friends"
  | "friends-of-friends"
  | "only-me";

const AUDIENCE_OPTIONS: {
  value: EventAudience;
  label: string;
  hint: string;
  icon: typeof Globe;
}[] = [
  { value: "public",             label: "Public",             hint: "Anyone on Mobigate can see this event.", icon: Globe },
  { value: "friends",            label: "Friends",            hint: "Only your friends can see this event.", icon: Users },
  { value: "friends-of-friends", label: "Friends of Friends", hint: "Your friends and their friends can see it.", icon: UserCheck },
  { value: "only-me",            label: "Only Me",            hint: "Private — only you can see this event.", icon: Lock },
];

export interface CreatedEvent {
  id: string;
  name: string;          // celebrant / honouree
  photo: string;         // cover image (first uploaded image, or initials fallback)
  images: string[];      // up to 3 uploaded photos/videos for the event
  dateLabel: string;     // e.g. "August 25"
  dateISO: string;       // YYYY-MM-DD
  eventType: CreatedEventType;
  eventLabel: string;    // human label
  notes?: string;
  audience: EventAudience;   // who can see this event
  isFriend: boolean;
  createdAt: string;
}

const EVENT_OPTIONS: { value: CreatedEventType; label: string }[] = [
  { value: "wedding",          label: "Wedding / Marriage" },
  { value: "burial",           label: "Burial" },
  { value: "graduation",       label: "Graduation" },
  { value: "matriculation",    label: "Matriculation" },
  { value: "child-dedication", label: "Child Dedication" },
  { value: "house-warming",    label: "House Warming" },
  { value: "naming-ceremony",  label: "Naming Ceremony" },
  { value: "coronation",       label: "Coronation" },
  { value: "anniversary",      label: "Anniversary" },
  { value: "award-nite",       label: "Award Nite" },
  { value: "birthday",         label: "Birthday" },
  { value: "convocation",      label: "Convocation" },
  { value: "inauguration",     label: "Inauguration" },
  { value: "investiture",      label: "Investiture" },
  { value: "induction",        label: "Induction" },
  { value: "initiation",       label: "Initiation" },
  { value: "swearing-in",      label: "Swearing-in" },
  { value: "title-conferment", label: "Title Conferment" },
  { value: "title-taking",     label: "Title Taking" },
  { value: "ordination",       label: "Ordination" },
  { value: "others",           label: "Others (specify)" },
];

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const formatHumanDate = (iso: string) => {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  if (!y || !m || !d) return iso;
  return `${MONTHS[m - 1]} ${d}`;
};

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onCreated?: (ev: CreatedEvent) => void;
}

export const CreateEventDialog = ({ isOpen, onClose, onCreated }: Props) => {
  const { toast } = useToast();
  const [name,      setName]      = useState("");
  const [type,      setType]      = useState<CreatedEventType>("wedding");
  const [customType, setCustomType] = useState("");
  const [dateISO,   setDateISO]   = useState("");
  const [notes,     setNotes]     = useState("");
  const [audience,  setAudience]  = useState<EventAudience>("public");
  const [images,    setImages]    = useState<string[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const todayISO = useMemo(() => {
    const d = new Date();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    return `${d.getFullYear()}-${mm}-${dd}`;
  }, []);

  const handlePickImages = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    if (files.length === 0) return;

    const remaining = MAX_IMAGES - images.length;
    if (remaining <= 0) {
      toast({
        title: "Maximum reached",
        description: `You can add up to ${MAX_IMAGES} images per event.`,
        variant: "destructive",
      });
      e.target.value = "";
      return;
    }

    const accepted = files.slice(0, remaining);
    if (files.length > remaining) {
      toast({
        title: "Some images skipped",
        description: `Only ${MAX_IMAGES} images are allowed — added the first ${remaining}.`,
      });
    }

    accepted.forEach((file) => {
      const reader = new FileReader();
      reader.onload = () => {
        if (typeof reader.result === "string") {
          // Optimistic: append each image as it finishes reading.
          setImages((prev) => (prev.length >= MAX_IMAGES ? prev : [...prev, reader.result as string]));
        }
      };
      reader.readAsDataURL(file);
    });

    e.target.value = "";
  };

  const removeImage = (idx: number) => {
    setImages((prev) => prev.filter((_, i) => i !== idx));
  };

  const reset = () => {
    setName("");
    setType("wedding");
    setCustomType("");
    setDateISO("");
    setNotes("");
    setImages([]);
    setSubmitting(false);
  };

  const close = () => {
    reset();
    onClose();
  };

  const canSubmit =
    name.trim().length >= 2 &&
    !!dateISO &&
    (type !== "others" || customType.trim().length >= 2);

  const handleSubmit = () => {
    if (!canSubmit) return;
    setSubmitting(true);

    const resolvedLabel =
      type === "others"
        ? customType.trim()
        : EVENT_OPTIONS.find(o => o.value === type)?.label ?? "Event";

    const id = `evt-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
    // Cover image: first uploaded photo when present, otherwise initials avatar.
    const initialsAvatar = `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(name.trim())}`;
    const photo = images[0] || initialsAvatar;

    const newEvent: CreatedEvent = {
      id,
      name: name.trim(),
      photo,
      images: [...images],
      dateLabel: formatHumanDate(dateISO),
      dateISO,
      eventType: type,
      eventLabel: resolvedLabel,
      notes: notes.trim() || undefined,
      isFriend: false,
      createdAt: new Date().toISOString(),
    };

    // ── Optimistic: prepend to window store + broadcast ──────────────────────
    if (typeof window !== "undefined") {
      const w = window as any;
      const existing: CreatedEvent[] = Array.isArray(w.__NOTABLE_EVENTS__) ? w.__NOTABLE_EVENTS__ : [];
      w.__NOTABLE_EVENTS__ = [newEvent, ...existing];
      window.dispatchEvent(new CustomEvent("notableEventCreated", { detail: newEvent }));
    }

    // Notify caller immediately
    onCreated?.(newEvent);

    toast({
      title: "Event created",
      description: `${resolvedLabel} for ${newEvent.name} on ${newEvent.dateLabel} is now live.`,
    });

    // ── Fire-and-forget backend persistence ──────────────────────────────────
    const API_BASE =
      (import.meta as any).env?.VITE_API_URL ||
      "https://angola-press.com/en/api";
    fetch(`${API_BASE}/events/create.php`, {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id:  id,
        name:       newEvent.name,
        event_type: type,
        event_label: resolvedLabel,
        event_date: dateISO,
        notes:      newEvent.notes ?? "",
        images:     newEvent.images,
      }),
    }).catch(() => { /* silent — optimistic */ });

    close();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(o) => !o && close()}>
      <DialogContent className="w-[calc(100vw-0.5rem)] sm:w-full sm:max-w-[520px] max-h-[92dvh] overflow-y-auto px-3 py-4 sm:p-6">
        <DialogHeader className="text-left pr-6">
          <DialogTitle className="text-lg font-bold break-words">Create Notable Event</DialogTitle>
          <DialogDescription className="text-[13px] leading-relaxed">
            Birthdays appear automatically from profile info. Add weddings, burials,
            graduations and other occasions here so friends can celebrate with you.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3.5 mt-2">
          {/* Celebrant / Honouree */}
          <div className="space-y-1.5">
            <Label htmlFor="ev-name" className="text-sm font-semibold">
              Celebrant / Honouree Name <span className="text-destructive">*</span>
            </Label>
            <Input
              id="ev-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Anthony Okafor Ejiro"
              className="text-base"
              maxLength={80}
            />
          </div>

          {/* Event type */}
          <div className="space-y-1.5">
            <Label className="text-sm font-semibold">
              Event Type <span className="text-destructive">*</span>
            </Label>
            <Select value={type} onValueChange={(v) => setType(v as CreatedEventType)}>
              <SelectTrigger className="text-base h-11">
                <SelectValue placeholder="Choose an event type" />
              </SelectTrigger>
              <SelectContent className="max-h-[60dvh] overflow-y-auto">
                {EVENT_OPTIONS.map(o => (
                  <SelectItem key={o.value} value={o.value} className="text-base">
                    {o.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {type === "others" && (
              <Input
                value={customType}
                onChange={(e) => setCustomType(e.target.value)}
                placeholder="Specify event (e.g. Anniversary)"
                className="text-base mt-2"
                maxLength={60}
              />
            )}
          </div>

          {/* Date */}
          <div className="space-y-1.5">
            <Label htmlFor="ev-date" className="text-sm font-semibold">
              Event Date <span className="text-destructive">*</span>
            </Label>
            <Input
              id="ev-date"
              type="date"
              value={dateISO}
              min={todayISO.slice(0, 4) + "-01-01"}
              onChange={(e) => setDateISO(e.target.value)}
              className="text-base h-11"
            />
            {dateISO && (
              <p className="text-[12px] text-muted-foreground">
                Shows on cards as <span className="font-semibold text-foreground">{formatHumanDate(dateISO)}</span>.
              </p>
            )}
          </div>

          {/* Event photos (up to 3) */}
          <div className="space-y-1.5">
            <Label className="text-sm font-semibold">
              Event Photos{" "}
              <span className="text-muted-foreground font-normal">(optional · up to {MAX_IMAGES})</span>
            </Label>
            <p className="text-[12px] text-muted-foreground leading-snug">
              Add real photos from the occasion — they appear on the event card and in full view.
            </p>

            <div className="grid grid-cols-3 gap-2">
              {images.map((src, idx) => (
                <div
                  key={idx}
                  className="relative aspect-square rounded-lg overflow-hidden border border-border bg-muted"
                >
                  <img src={src} alt={`Event photo ${idx + 1}`} className="w-full h-full object-cover" />
                  <button
                    type="button"
                    onClick={() => removeImage(idx)}
                    className="absolute top-1 right-1 h-6 w-6 rounded-full bg-black/60 text-white flex items-center justify-center hover:bg-black/80 active:scale-90 transition-all touch-manipulation"
                    aria-label={`Remove photo ${idx + 1}`}
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                  {idx === 0 && (
                    <span className="absolute bottom-1 left-1 rounded bg-primary px-1.5 py-0.5 text-[10px] font-bold text-primary-foreground">
                      Cover
                    </span>
                  )}
                </div>
              ))}

              {images.length < MAX_IMAGES && (
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="aspect-square rounded-lg border-2 border-dashed border-border bg-muted/40 flex flex-col items-center justify-center gap-1 text-muted-foreground hover:border-primary/50 hover:text-primary active:scale-[0.98] transition-all touch-manipulation"
                  aria-label="Add event photo"
                >
                  <ImagePlus className="h-6 w-6" />
                  <span className="text-[11px] font-semibold">Add Photo</span>
                </button>
              )}
            </div>

            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              multiple
              className="hidden"
              onChange={handlePickImages}
            />
            <p className="text-[11px] text-muted-foreground text-right">
              {images.length}/{MAX_IMAGES} added
            </p>
          </div>


          <div className="space-y-1.5">
            <Label htmlFor="ev-notes" className="text-sm font-semibold">
              Notes <span className="text-muted-foreground font-normal">(optional)</span>
            </Label>
            <Textarea
              id="ev-notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Venue, dress code, time — anything friends should know."
              className="text-[15px] min-h-[80px] resize-none"
              maxLength={280}
            />
            <p className="text-[11px] text-muted-foreground text-right">{notes.length}/280</p>
          </div>
        </div>

        <DialogFooter className="flex flex-col-reverse sm:flex-row sm:justify-end gap-2 pt-2">
          <Button variant="outline" onClick={close} className="w-full sm:w-auto" disabled={submitting}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={!canSubmit || submitting} className="w-full sm:w-auto font-bold">
            Publish Event
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default CreateEventDialog;
